pipeline {
    agent any

    stages {
        stage("CleanUp") {
            steps {
                deleteDir()
            }
        }
        stage("Build") {
            steps {
                echo "Faza Build"
            }
        }
        stage("Deploy") {
            steps {
                echo "Faza Deploy"
            }
        }
        stage("Test") {
            steps {
                echo "Faza Test"
            }
        }
        stage("Release") {
            steps {
                echo "Faza Release"
            }
        }
    }
}
